#!/bin/sh

set -e

: ${ADB:=adb}

if [ -z "$1" ]
then
	echo "usage: $0 pattern" >&2
	exit 2
fi

set -u

packages=$("$ADB" shell pm list packages | awk -F \: "/$1/ { print \$2 }")

if [ -z "$packages" ]
then
	echo "no suitable packages found" >&2
	exit 1
fi

for pkg in $packages
do
	"$ADB" shell pm uninstall $(echo $pkg | sed 's/^package://') >/dev/null || echo "failed to remove $pkg" >&2
done
